name: Run Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install molehill from source
      run: |
        cd molehill
        python3 -m venv venv && source venv/bin/activate
        pip install .


    - name: Run tests
      run: |
        source venv/bin/activate
        python -m pytest tests/
