name: Run Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install build requirements
      run: |
        sudo apt install automake build-essential cmake git libboost-dev libginac-dev libglpk-dev libgmp-dev libhwloc-dev libarchive-dev libxerces-c-dev libz3-dev

    - name: Install requirements from source
      run: |
        python3 -m venv venv && source venv/bin/activate
        pip install -r build-requirements.txt 
        mkdir prerequisites && cd prerequisites
        git clone https://github.com/moves-rwth/storm.git
        git clone https://github.com/moves-rwth/stormpy.git
        git clone https://github.com/randriu/synthesis.git
        mkdir storm/build && cd storm/build
        cmake ..
        make storm storm-cli storm-pomdp
        cd - && cd stormpy
        pip install . --config-settings=cmake.define.USE_STORM_DFT=OFF --config-settings=cmake.define.USE_STORM_GSPN=OFF --config-settings=cmake.define.STORM_DIR_HINT=../storm/build
        cd - && cd synthesis
        pip install . --no-build-isolation --config-settings=cmake.define.STORM_DIR_HINT=../storm/build

    - name: Install molehill from source
      run: |
        pip install -r build-requirements.txt
        pip install . --no-build-isolation

    
    - name: Install test requirements
      run: |
        source venv/bin/activate
        pip install matplotlib numpy scipy pytest nbval numpy

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m pytest tests/
