name: Run Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install build requirements
      run: |
        sudo apt install automake build-essential cmake git libboost-dev libginac-dev libglpk-dev libgmp-dev libhwloc-dev libarchive-dev libxerces-c-dev libz3-dev

    - name: Install molehill from source
      run: |
        python3 -m venv venv && source venv/bin/activate
        pip install .

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m pytest tests/
